apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: cluster-pod-1
    app: primeiro-pod
spec:
  containers:
  - name: container-pod-1
    image: nginx:latest
    ports:
      - containerPort: 80
