apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: cluster-pod-2
    app: segundo-pod
spec:
  containers:
  - name: container-pod-2
    image: nginx:latest
    ports:
      - containerPort: 80
