apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    name: portal-noticias-alura
    app: portal
spec:
  containers:
  - name: portal-noticias-container
    image: aluracursos/portal-noticias:1
    ports: 
      - containerPort: 80
